import { Image } from "expo-image";
import { Ionicons } from "@expo/vector-icons";
import { router, useLocalSearchParams } from "expo-router";
import { useMemo } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { getBrand, useBrands } from "../../lib/brands";
import { adaptBrandThemeToAppearance } from "../../lib/brandThemes";
import { clearBrandListingDraft, useBrandListingDrafts } from "../../lib/brandListingDraft";
import { themeFor } from "../../lib/brands";
import { useColors, useResolvedAppearance } from "../../lib/theme";

export default function BrandDrafts() {
  const { id } = useLocalSearchParams<{ id: string }>();
  useBrands();
  const brand = getBrand(id);
  const baseColors = useColors();
  const appearance = useResolvedAppearance();
  const palette = useMemo(() => { if (!brand) return { ...baseColors, bg: baseColors.ink, ink: baseColors.bone, card: baseColors.surface, accent: baseColors.success, accentInk: baseColors.successInk, lineColor: baseColors.subtle + "55" }; return adaptBrandThemeToAppearance(themeFor(brand), appearance, baseColors); }, [appearance, baseColors, brand]);
  const styles = useMemo(() => make(palette), [palette]);
  const insets = useSafeAreaInsets();
  const drafts = useBrandListingDrafts(id);
  if (!brand) return <View style={styles.page}><Text style={styles.title}>Brand not found</Text></View>;
  return <View style={styles.page}><ScrollView contentContainerStyle={[styles.content, { paddingTop: insets.top + 12, paddingBottom: insets.bottom + 30 }]} showsVerticalScrollIndicator={false}><View style={styles.topBar}><Pressable onPress={() => router.back()} style={styles.back} accessibilityRole="button" accessibilityLabel="Go back"><Ionicons name="arrow-back" size={21} color={palette.ink} /></Pressable><Text style={styles.pageName}>Drafts</Text><View style={styles.spacer} /></View><View style={styles.intro}><Text style={styles.title}>Pick up where you left off.</Text><Text style={styles.copy}>Unfinished brand listings are saved here automatically so you can continue when you’re ready.</Text></View>{drafts.length ? drafts.map((draft) => <View key={draft.id} style={styles.card}><View style={styles.preview}>{draft.photos[0]?.uri ? <Image source={{ uri: draft.photos[0].uri }} style={styles.previewImage} contentFit="cover" /> : <View style={styles.emptyImage}><Ionicons name="shirt-outline" size={26} color={palette.accent} /></View>}<View style={styles.draftBadge}><Text style={styles.draftBadgeText}>SAVED DRAFT</Text></View></View><View style={styles.cardBody}><Text style={styles.cardTitle} numberOfLines={2}>{draft.name.trim() || "Untitled brand item"}</Text><Text style={styles.cardMeta}>{draft.photos.length ? `${draft.photos.length} photo${draft.photos.length === 1 ? "" : "s"}` : "No photo yet"} · Updated {new Date(draft.updatedAt).toLocaleDateString()}</Text><View style={styles.progressTrack}><View style={[styles.progressFill, { width: `${progress(draft)}%` }]} /></View><Text style={styles.progressText}>{progress(draft)}% complete</Text><View style={styles.cardActions}><Pressable onPress={() => router.push({ pathname: "/brand/list", params: { id: brand.id, draftId: draft.id } })} style={styles.resume}><Text style={styles.resumeText}>Continue listing</Text><Ionicons name="arrow-forward" size={17} color={palette.accentInk} /></Pressable><Pressable onPress={() => Alert.alert("Delete draft?", "This saved brand listing will be removed.", [{ text: "Cancel", style: "cancel" }, { text: "Delete", style: "destructive", onPress: () => void clearBrandListingDraft(draft.id) }])} style={styles.delete} accessibilityLabel="Delete draft"><Ionicons name="trash-outline" size={18} color={palette.muted} /></Pressable></View></View></View>) : <View style={styles.empty}><Ionicons name="document-text-outline" size={29} color={palette.accent} /><Text style={styles.emptyTitle}>No saved drafts yet</Text><Text style={styles.emptyBody}>Start listing an item for {brand.name}. If you leave before publishing, it will appear here automatically.</Text><Pressable onPress={() => router.push({ pathname: "/brand/list", params: { id: brand.id } })} style={styles.start}><Text style={styles.startText}>Start a brand listing</Text></Pressable></View>}</ScrollView></View>;
}
function progress(draft: { photos: Array<unknown>; name: string; price: string; notes: string; category: unknown; picked: string[]; color: string; material: string }) { const checks = [draft.photos.length > 0, Boolean(draft.name.trim()), Number(draft.price) > 0, Boolean(draft.notes.trim()), Boolean(draft.category), draft.picked.length > 0, Boolean(draft.color.trim()), Boolean(draft.material.trim())]; return Math.round((checks.filter(Boolean).length / checks.length) * 100); }
function make(theme: { bg: string; ink: string; muted: string; card: string; accent: string; accentInk: string; lineColor: string }) { return StyleSheet.create({ page: { flex: 1, backgroundColor: theme.bg }, content: { paddingHorizontal: 20 }, topBar: { flexDirection: "row", alignItems: "center", minHeight: 44 }, back: { width: 40, height: 40, justifyContent: "center" }, pageName: { color: theme.ink, fontSize: 17, fontWeight: "800" }, spacer: { flex: 1 }, intro: { marginTop: 25, marginBottom: 24 }, title: { color: theme.ink, fontSize: 32, lineHeight: 37, fontWeight: "800", letterSpacing: -0.7 }, copy: { color: theme.muted, fontSize: 15, lineHeight: 22, marginTop: 9 }, card: { backgroundColor: theme.card, borderRadius: 19, overflow: "hidden", marginBottom: 13 }, preview: { height: 165, position: "relative", backgroundColor: theme.bg }, previewImage: { width: "100%", height: "100%" }, emptyImage: { flex: 1, alignItems: "center", justifyContent: "center" }, draftBadge: { position: "absolute", left: 12, bottom: 12, backgroundColor: theme.accent, borderRadius: 9, paddingHorizontal: 8, paddingVertical: 5 }, draftBadgeText: { color: theme.accentInk, fontSize: 9, letterSpacing: 1.2, fontWeight: "900" }, cardBody: { padding: 15 }, cardTitle: { color: theme.ink, fontSize: 18, fontWeight: "900" }, cardMeta: { color: theme.muted, fontSize: 12, marginTop: 5 }, progressTrack: { height: 5, backgroundColor: theme.bg, borderRadius: 3, overflow: "hidden", marginTop: 16 }, progressFill: { height: "100%", backgroundColor: theme.accent }, progressText: { color: theme.muted, fontSize: 10, marginTop: 6 }, cardActions: { flexDirection: "row", gap: 9, marginTop: 13 }, resume: { flex: 1, flexDirection: "row", alignItems: "center", justifyContent: "space-between", backgroundColor: theme.accent, borderRadius: 13, paddingHorizontal: 13, paddingVertical: 12 }, resumeText: { color: theme.accentInk, fontSize: 13, fontWeight: "900" }, delete: { width: 44, borderWidth: 1, borderColor: theme.lineColor, borderRadius: 13, alignItems: "center", justifyContent: "center" }, empty: { alignItems: "center", backgroundColor: theme.card, borderRadius: 19, padding: 28, marginTop: 5 }, emptyTitle: { color: theme.ink, fontSize: 18, fontWeight: "900", marginTop: 11 }, emptyBody: { color: theme.muted, fontSize: 13, lineHeight: 19, textAlign: "center", marginTop: 7 }, start: { backgroundColor: theme.accent, borderRadius: 13, paddingHorizontal: 16, paddingVertical: 12, marginTop: 18 }, startText: { color: theme.accentInk, fontSize: 13, fontWeight: "900" } }); }
