const FLAG_KEYS = [
  "aiGenerated",
  "isAiGenerated",
  "ai_generated",
  "is_ai_generated",
  "syntheticMedia",
  "synthetic_media",
  "isSynthetic",
  "is_synthetic",
];

const LABEL_KEYS = [
  "contentLabel",
  "content_label",
  "aiLabel",
  "ai_label",
  "mediaLabel",
  "media_label",
  "label",
  "labels",
];

export function aiGeneratedFromUnknown(value: unknown) {
  if (!value || typeof value !== "object") return false;
  const record = value as Record<string, unknown>;
  if (FLAG_KEYS.some((key) => record[key] === true)) return true;
  const labels = LABEL_KEYS.flatMap((key) => {
    const item = record[key];
    if (Array.isArray(item)) return item.map(String);
    return item == null ? [] : [String(item)];
  }).join(" ");
  return /\bai[\s_-]*generated\b|\bgenerated\s+by\s+ai\b|\bsynthetic\s+media\b|\bmade\s+with\s+ai\b/i.test(labels);
}

export const AI_CONTENT_LABEL = "AI-generated content";
export const AI_CONTENT_EXPLANATION =
  "This post was labeled as AI-generated by the social platform. Uvel keeps the label visible so you can tell when media may be synthetic or altered.";
