from pathlib import Path
import json

root = Path(__file__).resolve().parents[1]
data = json.loads((root / '.localization-packs.json').read_text())
out = root / 'lib' / 'generatedCopy.ts'
out.write_text(
    '// Generated by scripts/build-generated-copy.py. Do not edit by hand.\n'
    'import type { Copy } from "./i18n";\n\n'
    f'export const GENERATED_COPY: Record<string, Copy> = {json.dumps(data, ensure_ascii=False, indent=2)};\n'
)
print(out)
